/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WatchRouteImport } from './routes/watch'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WatchUserIdRouteImport } from './routes/watch.$userId'

const WatchRoute = WatchRouteImport.update({
  id: '/watch',
  path: '/watch',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchUserIdRoute = WatchUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => WatchRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/leaderboard': typeof LeaderboardRoute
  '/watch': typeof WatchRouteWithChildren
  '/watch/$userId': typeof WatchUserIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/leaderboard': typeof LeaderboardRoute
  '/watch': typeof WatchRouteWithChildren
  '/watch/$userId': typeof WatchUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/leaderboard': typeof LeaderboardRoute
  '/watch': typeof WatchRouteWithChildren
  '/watch/$userId': typeof WatchUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/leaderboard' | '/watch' | '/watch/$userId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/leaderboard' | '/watch' | '/watch/$userId'
  id: '__root__' | '/' | '/auth' | '/leaderboard' | '/watch' | '/watch/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  LeaderboardRoute: typeof LeaderboardRoute
  WatchRoute: typeof WatchRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/watch': {
      id: '/watch'
      path: '/watch'
      fullPath: '/watch'
      preLoaderRoute: typeof WatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch/$userId': {
      id: '/watch/$userId'
      path: '/$userId'
      fullPath: '/watch/$userId'
      preLoaderRoute: typeof WatchUserIdRouteImport
      parentRoute: typeof WatchRoute
    }
  }
}

interface WatchRouteChildren {
  WatchUserIdRoute: typeof WatchUserIdRoute
}

const WatchRouteChildren: WatchRouteChildren = {
  WatchUserIdRoute: WatchUserIdRoute,
}

const WatchRouteWithChildren = WatchRoute._addFileChildren(WatchRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  LeaderboardRoute: LeaderboardRoute,
  WatchRoute: WatchRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
